const skills = [
  {
    name: 'laravel',
    background1: '#F0150C',
    background2: '#FD8430',
    background3: '#D9162C',
    background4: '#E35B2B',
    color: '#fb503b',
    image: 'logos/laravel.png',
    icon: '../../logos/laravel.png',
    experience: '3',
  },
  {
    name: 'vue',
    background1: '#40CF66',
    background2: '#40CFB7',
    background3: '#40C43D',
    background4: '#3DB6C4',
    color: '#42b883',
    image: 'logos/vue.png',
    icon: '../../logos/vue.png',
    experience: '3',
  },
  {
    name: 'react',
    background1: '#5684FD',
    background2: '#56FDC2',
    background3: '#4D9EE3',
    background4: '#4DE3D9',
    color: '#5ed3f3',
    image: 'logos/react.png',
    icon: '../../logos/react.png',
    experience: '1',
  },
  // {
  //   name: 'express',
  //   background1: '#474044',
  //   background2: '#3D373D',
  //   background3: '#474140',
  //   background4: '#3D3937',
  //   color: '',
  //   image: 'logos/express.png',
  //   icon: '../../logos/express.png',
  //   experience: '',
  // },
  // {
  //   name: 'graphql',
  //   background1: '#FC2D50',
  //   background2: '#F23F2C',
  //   background4: '#FC2D50',
  //   background3: '#F23F2C',
  //   color: '',
  //   image: 'logos/graphql.png',
  //   icon: '../../logos/graphql.png',
  //   experience: '',
  // },
  {
    name: 'node',
    background1: '#87c149',
    background2: '#fff',
    background3: '#FD8430',
    background4: '#fff',
    color: '#53a044',
    image: 'logos/node.png',
    icon: '../../logos/node.png',
    experience: '1',
  },
  {
    name: 'tailwindcss',
    background1: '#18b1b4',
    background2: '#19abb4',
    background3: '#19abb4',
    background4: '#19abb4',
    color: '#36b7f0',
    image: 'logos/tailwindcss.png',
    icon: '../../logos/tailwindcss.png',
    experience: '1',
  },
  {
    name: 'bootstrap',
    background1: '#B862D9',
    background2: '#E366E3',
    background3: '#E36666',
    background4: '#D97362',
    color: '#523b77',
    image: 'logos/bootstrap.png',
    icon: '../../logos/bootstrap.png',
    experience: '2',
  },
  {
    name: 'sass',
    background1: '#B862D9',
    background2: '#E366E3',
    background3: '#E36666',
    background4: '#D97362',
    color: '#cf649a',
    image: 'logos/sass.png',
    icon: '../../logos/sass.png',
    experience: '1',
  },
  {
    name: 'figma',
    background1: '#18b1b4',
    background2: '#19abb4',
    background3: '#19abb4',
    background4: '#19abb4',
    color: '#a259ff',
    image: 'logos/figma.png',
    icon: '../../logos/figma.png',
    experience: '1',
  },
  {
    name: 'mongodb',
    background1: '#7FC93A',
    background2: '#A8BF37',
    background3: '#3AC953',
    background4: '#37BF76',
    color: '#54ad45',
    image: 'logos/mongo.png',
    icon: '../../logos/mongo.png',
    experience: '1',
  },
  {
    name: 'mysql',
    background1: '#08A698',
    background2: '#089C65',
    background3: '#085FA6',
    background4: '#fff',
    color: '#5d87a1',
    image: 'logos/mysql.png',
    icon: '../../logos/mysql.png',
    experience: '2',
  },
  {
    name: 'github',
    background1: '#332E30',
    background2: '#332E33',
    background3: '#332F2E',
    background4: '#332F2E',
    color: '#000000',
    image: 'logos/github.png',
    icon: '../../logos/github.png',
    experience: '3',
  },
  {
    name: 'gitlab',
    background1: '#e24329',
    background2: '#fc6d26',
    background3: '#FD8430',
    background4: '#E35B2B',
    color: '#e24329',
    image: 'logos/gitlab.png',
    icon: '../../logos/gitlab.png',
    experience: '3',
  },
]

export default skills;